name = input("ENTER YOUR NAME: ")
matric_no = input("ENTER YOUR MATRIC NUMBER: ")
age = input("ENTER YOUR AGE: ")
department = input("ENTER YOUR DEPARTMENT: ")
sex = input("ENTER YOUR SEX: ")
level = input("ENTER YOUR LEVEL: ")
session = input("ENTER SESSION: ")
isMuslim = input("ARE YOU A MUSLIM:\n ")

print("NAME: ",name)
print("MATRIC NO: ",matric_no)
print("AGE: ",age)
print("DEPARTMENT: ",department)
print("SEX: ",sex)
print("LEVEL: ",level)
print("SESSION: ",session)
print("MUSLIM: ",isMuslim)
